import json
import sys
from pathlib import Path

DEFAULT_TEST_CASE_PATH = Path("sample_outputs/login_test_case.json")
DEFAULT_OUTPUT_DIR = Path("playwright")
BASE_URL = "https://the-internet.herokuapp.com"


def read_json_file(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def generate_playwright_code(data: dict) -> str:
    feature_name = data.get("feature_name", "Unknown Feature")
    test_steps = data.get("test_steps", [])
    expected_results = data.get("expected_results", [])
    negative_cases = data.get("negative_cases", [])
    edge_cases = data.get("edge_cases", [])
    priority = data.get("priority", "-")
    risk_level = data.get("risk_level", "-")

    lines = []

    # 헤더
    lines.append(f"import {{ test, expect }} from '@playwright/test';")
    lines.append(f"")
    lines.append(f"/**")
    lines.append(f" * Feature: {feature_name}")
    lines.append(f" * Priority: {priority}")
    lines.append(f" * Risk Level: {risk_level}")
    lines.append(f" * Auto-generated by QA Agent MVP")
    lines.append(f" */")
    lines.append(f"")
    lines.append(f"const BASE_URL = '{BASE_URL}';")
    lines.append(f"")

    # Happy Path 테스트
    lines.append(f"test.describe('{feature_name}', () => {{")
    lines.append(f"")
    lines.append(f"  test('Happy Path - 정상 동작 확인', async ({{ page }}) => {{")
    lines.append(f"    await page.goto(BASE_URL);")
    lines.append(f"")
    lines.append(f"    // Test Steps")
    for step in test_steps:
        lines.append(f"    // {step}")
    lines.append(f"")
    lines.append(f"    // Expected Results")
    for result in expected_results:
        lines.append(f"    // TODO: {result}")
    lines.append(f"  }});")
    lines.append(f"")

    # Negative Cases
    if negative_cases:
        lines.append(f"  test.describe('Negative Cases', () => {{")
        lines.append(f"")
        for i, case in enumerate(negative_cases, 1):
            lines.append(f"    test('Negative {i}', async ({{ page }}) => {{")
            lines.append(f"      await page.goto(BASE_URL);")
            lines.append(f"      // {case}")
            lines.append(f"      // TODO: implement")
            lines.append(f"    }});")
            lines.append(f"")
        lines.append(f"  }});")
        lines.append(f"")

    # Edge Cases
    if edge_cases:
        lines.append(f"  test.describe('Edge Cases', () => {{")
        lines.append(f"")
        for i, case in enumerate(edge_cases, 1):
            lines.append(f"    test('Edge {i}', async ({{ page }}) => {{")
            lines.append(f"      await page.goto(BASE_URL);")
            lines.append(f"      // {case}")
            lines.append(f"      // TODO: implement")
            lines.append(f"    }});")
            lines.append(f"")
        lines.append(f"  }});")
        lines.append(f"")

    lines.append(f"}});")

    return "\n".join(lines)


def main() -> None:
    test_case_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_TEST_CASE_PATH

    if not test_case_path.exists():
        raise FileNotFoundError(f"테스트 케이스 파일이 없습니다: {test_case_path}")

    data = read_json_file(test_case_path)

    playwright_code = generate_playwright_code(data)

    stem = test_case_path.stem.replace("_test_case", "")
    output_path = DEFAULT_OUTPUT_DIR / f"{stem}.spec.ts"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(playwright_code, encoding="utf-8")

    print(f"Playwright 코드 생성 완료: {output_path}")


if __name__ == "__main__":
    main()